version: '3.9'

services:
  back-end-control-postgres:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwordd
      POSTGRES_DB: back-end-control
    volumes:
      - back-end-control-db:/var/lib/postgresql/back-end-control

volumes:
  back-end-control-db:
